CREATE TABLE TMWIN.KRC_MONTHLY_KPI_DATA (
  ID VARCHAR(7),
  MONTH TIMESTAMP,
  MILES INTEGER,
  AVG_DRIVERS INTEGER
)@
GRANT SELECT ON TABLE TMWIN.KRC_MONTHLY_KPI_DATA TO PUBLIC@
GRANT SELECT ON TABLE TMWIN.KRC_MONTHLY_KPI_DATA TO PUBLIC@
GRANT SELECT ON TABLE TMWIN.KRC_MONTHLY_KPI_DATA TO PUBLIC@
GRANT SELECT ON TABLE TMWIN.KRC_MONTHLY_KPI_DATA TO PUBLIC@
